Default cidr blocks to empty list
cloudposse/terraform-aws-security-group pull request #28
Opened 2021-12-13 19:23 UTC by nitrocode

## what
* Default cidr blocks to empty list

## why
* Otherwise on each plan, this is shown for each sg rule

```hcl
  # module.msk_cluster.module.broker_security_group.aws_security_group_rule.keyed["_m[0]#tls#sg#0"] has been changed
  ~ resource "aws_security_group_rule" "keyed" {
      + cidr_blocks              = []
        id                       = "sgrule-snip"
      + ipv6_cidr_blocks         = []
        # (9 unchanged attributes hidden)
    }
```

## references
N/A

2021-12-13 19:37 UTC, nitrocode commented
/test all

2021-12-28 22:34 UTC, aknysh approved these changes

2021-12-29 02:38 UTC, aknysh requested changes
this actually will not work since some of the fields conflict with each other.
we'll have to redesign the module to support that

2022-05-10 20:28 UTC, Nuru commented
Closing because this plan drift is a provider issue and is not possible to solve because you cannot supply both `cidr_block` and `ipv6_cidr_block` at the same time, even if either or both of them are empty lists.

2022-05-10 20:28 UTC, closed without merging